In [1]:
import numpy as np

In [2]:
input_vector_X = np.array([[0.1,0.2,0.3]]) #input a row vector
input_vector_X = np.transpose(input_vector_X) #transpose into a column vector with dimension 3x1
print("The input vector:\n", input_vector_X, "\n")
print("Input vector has shape (m,n):", input_vector_X.shape)

The input vector:
 [[0.1]
 [0.2]
 [0.3]] 

Input vector has shape (m,n): (3, 1)


In [3]:
weight_matrix_W = np.array([[0.65,0.10,0.85],[0.10,0.25,0.32],[0.3,0.3,0.45],[0.45,0.45,0.85]]) 

print("The weight matrix:\n", weight_matrix_W, "\n")
print("Weight matrix has shape (m,n):", weight_matrix_W.shape)

The weight matrix:
 [[0.65 0.1  0.85]
 [0.1  0.25 0.32]
 [0.3  0.3  0.45]
 [0.45 0.45 0.85]] 

Weight matrix has shape (m,n): (4, 3)


In [4]:
output_vector_Y = np.dot(weight_matrix_W,input_vector_X)

print("The output vector:\n", output_vector_Y, "\n")
print("Output vector has shape (m,n):", output_vector_Y.shape)

The output vector:
 [[0.34 ]
 [0.156]
 [0.225]
 [0.39 ]] 

Output vector has shape (m,n): (4, 1)
